### ISSUE TITLE
Put the downloads in Releases

### ISSUE THREAD

**Issue by fadden** [RetroDotLive/FuckerTalkX#1]
I'm delighted to see that both the technology and, shall we say, spirit of XBAND live on. :-)

One suggestion: don't put the binaries in the source tree.  Go to the Releases tab and create a new release, and drag&drop the zips over.  Otherwise git will have to maintain an eternal version-controlled collection of the binaries.

**Comment by RetroDotLive** [comment]
Thanks Andy! Great to hear from you. Hope everything is well. Shoot me a mail sometime
